using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace WASdkAPI
{
    /// <summary>
    /// 分享图片数据实体类
    /// </summary>
    public class WASharePhoto
    {
        private Uri imageUri;
        private bool userGenerated;
        private string caption;

        public WASharePhoto(Builder builder)
        {
            imageUri = builder.imageUri;
            userGenerated = builder.userGenerated;
            caption = builder.caption;
        }

        /// <summary>
        /// 将C#的WASharePhoto对象转换成Java中WASharePhoto类型AndroidJavaObject对象
        /// </summary>
        /// <returns></returns>
        public AndroidJavaObject toAndroidJavaObject()
        {
            AndroidJavaObject javaObjectBuilder = new AndroidJavaObject("com.wa.sdk.social.model.WASharePhoto$Builder");
            javaObjectBuilder.Call<AndroidJavaObject>("setImageUri", Utils.uriToAndroidJavaObject(imageUri));
            javaObjectBuilder.Call<AndroidJavaObject>("setUserGenerated", userGenerated);
            javaObjectBuilder.Call<AndroidJavaObject>("setCaption", caption);
            return javaObjectBuilder.Call<AndroidJavaObject>("build");
        }

        /// <summary>
        /// WASharePhoto Builder
        /// </summary>
        public class Builder
        {
            public Uri imageUri;
            public bool userGenerated;
            public string caption;

            /// <summary>
            /// Sets the URL to the photo.
            /// </summary>
            /// <param name="imageUri"> Uri that points to a network location or the location of the photo on disk.</param>
            /// <returns>The builder.</returns>
            public Builder setImageUri(Uri imageUri)
            {
                this.imageUri = imageUri;
                return this;
            }

            /// <summary>
            /// Sets whether the photo represented by this object was generated by the user or by the application.
            /// </summary>
            /// <param name="userGenerated">Indication of whether the photo is user-generated.</param>
            /// <returns>The builder.</returns>
            public Builder setUserGenerated(bool userGenerated)
            {
                this.userGenerated = userGenerated;
                return this;
            }

            /// <summary>
            /// Sets the user generated caption for the photo. Note that the 'caption' must come from
            /// the user, as pre-filled content is forbidden by the Platform Policies(2.3).
            /// </summary>
            /// <param name="caption">string of a WASharePhoto</param>
            /// <returns>The builder.</returns>
            public Builder setCaption(string caption)
            {
                this.caption = caption;
                return this;
            }

            public WASharePhoto build()
            {
                return new WASharePhoto(this);
            }
        }
    }
}
